#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Audiotica.Android.Resource", IsApplication=true)]

namespace Audiotica.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::Audiotica.Android.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::Audiotica.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060002
			public const int activity_horizontal_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int activity_vertical_margin = 2131099651;
			
			// aapt resource value: 0x7f060035
			public const int app_widget_bottom_margin = 2131099701;
			
			// aapt resource value: 0x7f060028
			public const int app_widget_large_alternate_artwork_size = 2131099688;
			
			// aapt resource value: 0x7f060025
			public const int app_widget_large_min_height = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int app_widget_large_min_width = 2131099684;
			
			// aapt resource value: 0x7f060034
			public const int app_widget_padding = 2131099700;
			
			// aapt resource value: 0x7f060030
			public const int app_widget_recents_action_bar_height = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int app_widget_recents_action_bar_item_padding = 2131099697;
			
			// aapt resource value: 0x7f060026
			public const int app_widget_scrollable_min_height = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int app_widget_scrollable_min_resize_height = 2131099687;
			
			// aapt resource value: 0x7f06002d
			public const int app_widget_small_artwork_size = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int app_widget_small_button_height = 2131099695;
			
			// aapt resource value: 0x7f06002e
			public const int app_widget_small_button_padding = 2131099694;
			
			// aapt resource value: 0x7f06002b
			public const int app_widget_small_info_container_padding_left = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int app_widget_small_info_container_padding_right = 2131099692;
			
			// aapt resource value: 0x7f06002a
			public const int app_widget_small_min_height = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int app_widget_small_min_width = 2131099689;
			
			// aapt resource value: 0x7f060032
			public const int app_widget_tiny_height = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int app_widget_tiny_width = 2131099699;
			
			// aapt resource value: 0x7f06000c
			public const int footer_thumbnail = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int image_height_vmlimit = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int image_width_vmlimit = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int kitkat_nav_bar_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int kitkat_nav_bar_margin_large = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int large_widget_album_art_size = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int list_padding = 2131099662;
			
			// aapt resource value: 0x7f060036
			public const int list_view_left_icon_size = 2131099702;
			
			// aapt resource value: 0x7f06001c
			public const int notification_action_height = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int notification_action_padding = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int notification_action_width = 2131099677;
			
			// aapt resource value: 0x7f060017
			public const int notification_big_icon_height = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int notification_big_icon_width = 2131099672;
			
			// aapt resource value: 0x7f060020
			public const int notification_expanded_button_height = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int notification_expanded_button_padding = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int notification_expanded_buttons_divider_padding = 2131099679;
			
			// aapt resource value: 0x7f060023
			public const int notification_expanded_collapse_padding = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int notification_expanded_content_padding_top = 2131099682;
			
			// aapt resource value: 0x7f06001e
			public const int notification_expanded_height = 2131099678;
			
			// aapt resource value: 0x7f06000b
			public const int notification_height = 2131099659;
			
			// aapt resource value: 0x7f06001a
			public const int notification_info_container_padding_bottom = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int notification_info_container_padding_left = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int playlist_preview = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int quickplay_offset = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int shadow_width = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int slidingmenu_offset = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int text_size_dayum = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int text_size_extra_micro = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int text_size_large = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int text_size_medium = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int text_size_micro = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int text_size_small = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int text_size_x_large = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int widget_list_view_art_size = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int widget_margin = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_notification_collapse = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_playback_next = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_playback_next_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_playback_pause = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_playback_pause_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_playback_play = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_playback_play_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_playback_previous = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_playback_previous_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_playback_repeat = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_playback_repeat_all = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_playback_repeat_one = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_playback_shuffle = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_playback_shuffle_all = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int card_gridview_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int card_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ElectricDaisyCarnival = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_action_overflow_universal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Icon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int MissingArtwork = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int NotifIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int transparent_drawable = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001c
			public const int artistNameSongListView = 2131230748;
			
			// aapt resource value: 0x7f080005
			public const int empty_view_text = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int fragment_artists_layout = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int generalListView = 2131230724;
			
			// aapt resource value: 0x7f08001e
			public const int linearLayout1 = 2131230750;
			
			// aapt resource value: 0x7f080003
			public const int list_fragment_front_layout = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int notification_base = 2131230736;
			
			// aapt resource value: 0x7f080017
			public const int notification_base_collapse = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int notification_base_image = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int notification_base_line_one = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int notification_base_line_two = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int notification_base_next = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int notification_base_play = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int notification_base_previous = 2131230740;
			
			// aapt resource value: 0x7f08000c
			public const int notification_expanded_base_collapse = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int notification_expanded_base_image = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int notification_expanded_base_line_one = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int notification_expanded_base_line_three = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int notification_expanded_base_line_two = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int notification_expanded_base_next = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int notification_expanded_base_play = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int notification_expanded_base_previous = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int notification_expanded_buttons = 2131230728;
			
			// aapt resource value: 0x7f08001d
			public const int overflow_icon = 2131230749;
			
			// aapt resource value: 0x7f080002
			public const int search_field = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int search_layout = 2131230721;
			
			// aapt resource value: 0x7f080019
			public const int songCardContent = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int songDurationListView = 2131230746;
			
			// aapt resource value: 0x7f080006
			public const int songListView = 2131230726;
			
			// aapt resource value: 0x7f08001b
			public const int songNameListView = 2131230747;
			
			// aapt resource value: 0x7f080018
			public const int songsListAlbumThumbnail = 2131230744;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int num_cols = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_list_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_custom_expanded_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_custom_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int songs_list_view_cards_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int songs_list_view_layout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int close_other_audio_apps = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int no_songs_found_info = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int NotificationAction = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int NotificationAction_Collapse = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int NotificationAction_Next = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int NotificationAction_Play = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int NotificationAction_Previous = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int NotificationText = 2131034117;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
